---
- name: Add NOPASSWD entry to sudoers
  hosts: ubuntu
  become: yes

  tasks:
    - name: Add NOPASSWD entry to sudoers
      lineinfile:
        dest: /etc/sudoers
        line: 'ansibleuser ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      notify:
        - Restart sudoers

  handlers:
    - name: Restart sudoers
      service:
        name: sudo
        state: restarted
