---
- hosts: localhost
  tasks:
  - name: Deploy Portainer
    docker_container:
      name: portainer
      image: portainer/portainer-ce
      ports:
        - "9000:9000"
        - "8000:8000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /mnt/ssd/portainer:/data
        - /etc/localtime:/etc/localtime:ro
      restart_policy: always


