---
- hosts: localhost
  become: true
  tasks:
    - name: Remove old docker packages 
      apt:
        name: foo
        state: absent
      loop:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc 
    - name: install dependacies 
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: add archive 
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        - docker-buildx-plugin
    - name: make sure docker is active 
      service:
        name: docker
        state: started
        enabled: yes

  handlers:
    - name: restart docker
      service: 
        name: docker 
        state: restarted

