---
- hosts: localhost
  become: true
  tasks:
  - name: Download k3s install script
    ansible.builtin.get_url:
      url: https://get.k3s.io
      dest: /tmp/getk3s.io
      mode: '+x'
  - name: Execute the command in remote shell; stdout goes to the specified file on the remote
    shell: /tmp/getk3s.io >> /tmp/getk3s_output.txt
  - name: Display getk3s_output.txt contents
    command: cat /tmp/getk3s_output.txt 
    register: command_output
  - name: Print to console
    debug:
      msg: "{{command_output.stdout}}"
  - name: start k3s
    service:
      name: k3s
      state: started
#sudo k3s kubectl config view --raw > ~/.kube/config

  handlers:
    - name: restart k3s
      service:
        name: k3s
        state: restarted

