---
- name: Install K3s on master
  hosts: k8smaster
  become: yes
  become_user: root
  tasks:
    - name: Install K3s on master
      shell: "curl -sfL https://get.k3s.io | sh -"
      #shell: 'curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server --disable=traefik" sh -'

- name: Get K3s Token
  hosts: k8smaster
  become: yes
  become_user: root
  tasks:
    - name: Get K3s Token
      command: "sudo cat /var/lib/rancher/k3s/server/node-token"
      register: k3s_token


- name: Install K3s on slaves
  hosts: k8sworker
  become: yes
  become_user: root
  tasks:
    - name: Install K3s on workers
      shell: "curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['ubuntu-node01'].ansible_host }}:6443 K3S_TOKEN={{ hostvars['ubuntu-node01'].k3s_token.stdout_lines.0 }} sh -"

