---
- name: Get join command from master
  hosts: k8smaster
  become: true
  tasks:
    - name: Get join command
      ansible.builtin.command:
        cmd: kubeadm token create --print-join-command
      register: join_command
      changed_when: false

- name: Join worker nodes to the cluster
  hosts: k8sworker
  become: true
  tasks:
    - name: Join the cluster
      ansible.builtin.command:
        cmd: "{{ hostvars[groups['k8smaster'][0]].join_command.stdout }}"
        creates: /etc/kubernetes/kubelet.conf