---
- name: Enable IP Forwarding
  hosts: ubuntu
  become: yes

  tasks:
    - name: Uncomment net.ipv4.ip_forward in sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^#?net.ipv4.ip_forward\s*=\s*1$'
        line: 'net.ipv4.ip_forward = 1'
        state: present

    - name: Reload sysctl configuration
      command: sysctl -p
