---
- name: Install nfs Ubuntu
  hosts: localhost
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install required nfs kernalE
      apt:
        name:
          - nfs-kernel-server
          - nfs-common
        state: present

    - name: Create directory for NFS share
      ansible.builtin.file:
        path: /mnt/pve/nvme1/share
        state: directory
   
    - name: Configure NFS export
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: "/mnt/pve/nvme1/share  192.168.86.0/24(rw,sync,no_subtree_check)"
        state: present
      notify: Restart NFS

  handlers:
    - name: Restart NFS
      service:
        name: nfs-kernel-server
        state: restarted
