---
- name: Install Docker CE on Ubuntu
  hosts: "{{ docker_hosts | default('ubuntu') }}"
  become: true

  vars:
    # You can override the target hosts by passing `-e "docker_hosts=your_host_group"`
    docker_hosts: ubuntu
    # Set this to false if you don't want to add ansibleuser to the docker group
    add_ansibleuser_to_docker_group: true

  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages for Docker CE
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Install Docker CE
      ansible.builtin.apt:
        name: docker-ce
        state: present

    - name: Add ansibleuser to the docker group
      ansible.builtin.user:
        name: ansibleuser
        groups: docker
        append: yes
      when: add_ansibleuser_to_docker_group